PROGRAM = main
OUTPUT = $(PROGRAM)
LOCOBJS = EmptyParticle.o GlauberEventPar.o
#GSL_PATH=/scratch/galette/bierlich/tools/gsl
#MINUIT_PATH=/scratch/galette/bierlich/Dropbox/analysis/panf/minuit/Minuit2-5.28.00/
COMMON = ../windu/
#TEMPLS = $(shell python ../panf/dictwriter.py templ)
include $(COMMON)Makefile.common