PROGRAM = main
OUTPUT = $(PROGRAM)
LOCOBJS = EmptyParticle.o GlauberEventPar.o
GSL_PATH=/Users/bierlich/tools/gsl/
MINUIT_PATH=/Users/bierlich/tools/windu/minuit/Minuit2-5.28.00/
COMMON = ../windu/
#TEMPLS = $(shell python ../panf/dictwriter.py templ)
include $(COMMON)Makefile.common