/********************************************************************
* mainDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error mainDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemainDict();
extern void G__cpp_setup_inheritancemainDict();
extern void G__cpp_setup_typetablemainDict();
extern void G__cpp_setup_memvarmainDict();
extern void G__cpp_setup_globalmainDict();
extern void G__cpp_setup_memfuncmainDict();
extern void G__cpp_setup_funcmainDict();
extern void G__set_cpp_environmentmainDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../common/AbsEvent.h"
#include "../common/HiEvent.h"
#include "../common/AbsInventory.h"
#include "../common/Inventory.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mainDictLN_TClass;
extern G__linked_taginfo G__mainDictLN_TBuffer;
extern G__linked_taginfo G__mainDictLN_TMemberInspector;
extern G__linked_taginfo G__mainDictLN_TObject;
extern G__linked_taginfo G__mainDictLN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__mainDictLN_string;
extern G__linked_taginfo G__mainDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__mainDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mainDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__mainDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mainDictLN_AbsEvent;
extern G__linked_taginfo G__mainDictLN_Particle;
extern G__linked_taginfo G__mainDictLN_HiEvent;
extern G__linked_taginfo G__mainDictLN_vectorlEParticlecOallocatorlEParticlegRsPgR;
extern G__linked_taginfo G__mainDictLN_vectorlEParticlecOallocatorlEParticlegRsPgRcLcLiterator;
extern G__linked_taginfo G__mainDictLN_reverse_iteratorlEvectorlEParticlecOallocatorlEParticlegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mainDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__mainDictLN_TTree;
extern G__linked_taginfo G__mainDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__mainDictLN_AbsInventory;
extern G__linked_taginfo G__mainDictLN_Inventory;

/* STUB derived class for protected member access */
typedef vector<Particle,allocator<Particle> > G__vectorlEParticlecOallocatorlEParticlegRsPgR;
