PROGRAM = main
OUTPUT = $(PROGRAM)
LOCOBJS = EmptyParticle.o GlauberEventPar.o GlauberChi2.o
COMMON = /scratch/galette/bierlich/tools/windu/windu/
#TEMPLS = $(shell python ../panf/dictwriter.py templ)
include $(COMMON)Makefile.common